# StreamFi/docker-compose.yml

services:
  # Database Service (MongoDB)
  db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - streamfi-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node Media Server
  nms:
    build:
      context: ./packages/media-server
      dockerfile: Dockerfile
    ports:
      - "1935:1935"   # RTMP ingest
      - "8081:8080"   # HLS HTTP (host:container)
    env_file:
      - ./packages/backend/.env
    networks:
      - streamfi-net

  # Backend Service
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./packages/backend/.env
    depends_on:
      db:
        condition: service_healthy
      nms:
        condition: service_started
    environment: {}
    networks:
      - streamfi-net

  # Frontend Service
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
        NEXT_PUBLIC_HLS_BASE: ${NEXT_PUBLIC_HLS_BASE}
        NEXT_PUBLIC_CHAT_WS_BASE: ${NEXT_PUBLIC_CHAT_WS_BASE}
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    env_file:
      - ./packages/frontend/.env.local
    environment:
      BACKEND_URL: http://backend:8000
    networks:
      - streamfi-net

networks:
  streamfi-net:
    driver: bridge

volumes:
  mongo_data:
