services:
  # Node Media Server
  nms:
    build:
      context: ./packages/media-server
      dockerfile: Dockerfile
    ports:
      - "1935:1935"   # RTMP ingest
      - "8081:8080"   # HLS HTTP (external:internal)
    env_file:
      - ./packages/media-server/.env   # keep NMS-specific envs here
    networks:
      - streamfi-net

  # Backend Service
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./packages/backend/.env
    depends_on:
      - nms
    networks:
      - streamfi-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend Service
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: /api
        NEXT_PUBLIC_HLS_BASE: http://localhost:8081
        NEXT_PUBLIC_CHAT_WS_BASE: /socket.io
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./packages/frontend/.env.local
    environment:
      BACKEND_URL: http://backend:8000
    networks:
      - streamfi-net

networks:
  streamfi-net:
    driver: bridge
